---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cuberite/docker-build-image

inputs:
- name: built-cuberite-master-src

outputs:
- name: artifacts-cuberite-master-src

run:
  path: tar
  args:
  - -zcvf
  - ../artifacts-cuberite-master-src/cuberite.tar.gz
  - Server
  dir: built-cuberite-master-src
