resources:
- name: resource-cuberite-master-src
  type: git
  source:
    uri: https://github.com/cuberite/cuberite
    branch: master
- name: resource-cuberite-concourse
  type: git
  source:
    uri: https://github.com/cuberite/concourse
    branch: master


jobs:
- name: job-build-cuberite-master
  plan:
  - get: resource-cuberite-concourse
    trigger: true
  - get: resource-cuberite-master-src
    trigger: true
  - task: cmake
    file: resource-cuberite-concourse/tasks/cmake.yml
