---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
- name: built-cuberite-master-src

outputs:
- name: artifacts-cuberite-master-src

run:
  path: ls
  args: [-la]
  dir: built-cuberite-master-src
