---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
- name: resource-cuberite-master-src
- name: cmake-prepared-cuberite-master-src

outputs:
- name: built-cuberite-master-src

run:
  path: make
  args: [-j4]
  dir: cmake-prepared-cuberite-master-src
