---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
- name: resource-cuberite-master-src
- name: resource-cuberite-concourse

outputs:
- name: built-cuberite-master-src

run:
  path: ls
  args: [-la]
  dir: built-cuberite-master-src
