---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
- name: resource-cuberite-master-src

outputs:
- name: built-cuberite-master-src

run:
  path: ../scripts/build-master.sh
  dir: built-cuberite-master-src
