---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
  - name: resource-cuberite-master-src

outputs:
  - name: resource-cuberite-master-src

run:
  path: make
  dir: resource-cuberite-master-src
