---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
  - name: cmaked-cuberite-master-src

outputs:
  - name: built-cuberite-master-src

run:
  path: ls
  dir: cmaked-cuberite-master-src
