---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: andystanton/gcc-cmake-gls

inputs:
  - name: resource-cuberite-master-src

outputs:
  - name: cmaked-cuberite-master-src

run:
  path: cmake
  args: [.]
  dir: resource-cuberite-master-src
