---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
- name: resource-cuberite-master-src

outputs:
- name: cmake-prepared-cuberite-master-src

run:
  path: cmake
  args: [.]
  dir: resource-cuberite-master-src
