---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: buildpack-deps

inputs:
  - name: resource-cuberite-master-src

outputs:
  - name: cmaked-cuberite-master-src

run:
  path: ls
  args: [-la]
  dir: resource-cuberite-master-src
