---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kaskada/cmake-gcc5

inputs:
- name: built-cuberite-release-src

outputs:
- name: artifacts-cuberite-release-src

run:
  path: tar
  args:
  - -zcvf
  - ../artifacts-cuberite-release-src/cuberite.tar.gz
  - Server
  dir: built-cuberite-release-src
