---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cuberite/docker-build-image

inputs:
- name: resource-cuberite-release-src
- name: resource-cuberite-concourse

outputs:
- name: built-cuberite-release-src

run:
  path: ../resource-cuberite-concourse/tasks/release/build.sh
  dir: resource-cuberite-release-src
